"""add title and text to notifications

Revision ID: eb6f865c65bf
Revises: 
Create Date: 2024-06-04 12:54:40.751923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6f865c65bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('notifications', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'text')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
